# -*- coding: utf-8 -*-
import array

# Form implementation generated from reading ui file '.\gui_phones_extractor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QFont
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QWidget, QLabel
from PyQt5.QtCore import QThread, pyqtSignal, QRect
from scraper.scrape_amazon import ScrapeAmazon
import pandas as pd
from urllib.parse import urlparse
import subprocess
import os
import json

basedir = os.path.dirname(__file__)
class Ui_MainWindow(object):
    csv_path = ""
    csv_to_read = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 520)
        MainWindow.setFixedSize(MainWindow.size())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily("RussellSquare")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 57 16pt \"RussellSquare\";")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 320, 491, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 60, 491, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 99, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 410, 481, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.btn_extract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_extract.setGeometry(QtCore.QRect(120, 350, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.btn_extract.setFont(font)
        self.btn_extract.setText("Extract")
        self.btn_extract.setObjectName("btn_extract")
        self.lbl_message = QtWidgets.QLabel(self.centralwidget)
        self.lbl_message.setGeometry(QtCore.QRect(230, 300, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_message.setFont(font)
        self.lbl_message.setStyleSheet("color:rgb(255, 0, 0)")
        self.lbl_message.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_message.setObjectName("lbl_message")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_pages = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_pages.setGeometry(QtCore.QRect(190, 140, 351, 22))
        self.comboBox_pages.setObjectName("comboBox_pages")
        self.comboBox_pages.addItem("")
        self.comboBox_pages.addItem("")
        self.comboBox_pages.addItem("")
        self.comboBox_pages.addItem("")
        self.comboBox_pages.addItem("")
        self.comboBox_pages.addItem("")
        self.checkBox_ships = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ships.setGeometry(QtCore.QRect(30, 220, 161, 17))
        self.checkBox_ships.setObjectName("checkBox_ships")
        self.checkBox_sold = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_sold.setGeometry(QtCore.QRect(30, 250, 161, 17))
        self.checkBox_sold.setObjectName("checkBox_sold")
        self.comboBox_stars = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stars.setGeometry(QtCore.QRect(190, 180, 351, 22))
        self.comboBox_stars.setObjectName("comboBox_stars")
        self.comboBox_stars.addItem("")
        self.comboBox_stars.addItem("")
        self.comboBox_stars.addItem("")
        self.comboBox_stars.addItem("")
        self.comboBox_stars.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox_price = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_price.setGeometry(QtCore.QRect(30, 280, 81, 17))
        self.checkBox_price.setObjectName("checkBox_price")
        self.text_price_min = QtWidgets.QLineEdit(self.centralwidget)
        self.text_price_min.setGeometry(QtCore.QRect(190, 280, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_price_min.setFont(font)
        self.text_price_min.setObjectName("text_price_min")
        self.text_price_min_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_price_min_2.setGeometry(QtCore.QRect(390, 280, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_price_min_2.setFont(font)
        self.text_price_min_2.setObjectName("text_price_min_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.progressBar.setProperty("value", 0)
        self.lbl_message.setVisible(False)
        # btn open file
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(230, 440, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, 'icons/open.ico')), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open.setIcon(icon)
        self.btn_open.setObjectName("btn_open")
        self.btn_open.setVisible(False)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Events
        self.btn_extract.clicked.connect(self.on_click_extract)
        self.actionAbout.triggered.connect(self.onClickAbout)
        self.btn_open.clicked.connect(self.onClickOpenFile)

    def on_click_extract(self):
        if self.lineEdit.text() == "":
            self.showMessageBox("warning", "Please, enter a product name")
        else:
            print(self.comboBox_pages.currentText())
            print(self.comboBox_stars.currentText())
            print(self.checkBox_ships.checkState())
            print(self.checkBox_sold.checkState())
            self.progressBar.setVisible(True)
            self.extract_thread = ExtractThread(self.lineEdit.text(), self.comboBox_pages.currentText(), self.checkBox_sold.checkState(), self.checkBox_ships.checkState(), self.comboBox_stars.currentText())
            self.extract_thread.signal_pbar.connect(self.updateProgressBar)
            self.extract_thread.signal_save_csv.connect(self.saveCSVFile)
            self.extract_thread.signal_messagebox.connect(self.showMessageBox)
            self.extract_thread.start()



    def showMessageBox(self, type, message):
        qw = QWidget()
        if type == "warning":
            QMessageBox.warning(qw, "Phone extractor", message)
        elif type == "information":
            QMessageBox.information(qw, "Phone extractor", message)
        elif type == "error":
            QMessageBox.critical(qw, "Phone extractor", message)
        else:
            QMessageBox.information(qw, "Phone extractor", message)
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Amazon extractor"))
        self.label.setText(_translate("MainWindow", "Amazon extractor"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "example: dell laptop"))
        self.lbl_message.setText(_translate("MainWindow", "Example text label"))
        self.label_2.setText(_translate("MainWindow", "Product name"))
        self.label_3.setText(_translate("MainWindow", "Pages"))
        self.comboBox_pages.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_pages.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_pages.setItemText(2, _translate("MainWindow", "10"))
        self.comboBox_pages.setItemText(3, _translate("MainWindow", "15"))
        self.comboBox_pages.setItemText(4, _translate("MainWindow", "20"))
        self.comboBox_pages.setItemText(5, _translate("MainWindow", "All"))
        self.checkBox_ships.setText(_translate("MainWindow", "Only ships from Amazon"))
        self.checkBox_sold.setText(_translate("MainWindow", "Only sold by from Amazon"))
        self.comboBox_stars.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox_stars.setItemText(1, _translate("MainWindow", "1 & up"))
        self.comboBox_stars.setItemText(2, _translate("MainWindow", "2 & up"))
        self.comboBox_stars.setItemText(3, _translate("MainWindow", "3 & up"))
        self.comboBox_stars.setItemText(4, _translate("MainWindow", "4 & up"))
        self.label_4.setText(_translate("MainWindow", "Stars"))
        self.checkBox_price.setText(_translate("MainWindow", "Price range"))
        self.text_price_min.setPlaceholderText(_translate("MainWindow", "$ Min"))
        self.text_price_min_2.setPlaceholderText(_translate("MainWindow", "$ Max"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About "))
        self.btn_open.setText(_translate("MainWindow", "Open file"))

    def saveCSVFile(self, array_products, csv_name):
        dir_csv = 'data_output'
        json_string = json.dumps(array_products)
        df = pd.read_json(json_string, orient='records')
        df.to_csv(f'{dir_csv}/{csv_name}.csv', index=False, encoding='utf-8-sig')
        self.btn_open.setVisible(True)
        self.csv_path = f'{os.getcwd()}\data_output\{csv_name}.csv'

    def updateProgressBar(self, value):
        self.progressBar.setProperty("value", value)

    def onClickAbout(self):
        self.WAbout = WindowAbout()
        self.WAbout.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        self.WAbout.show()

    def onClickOpenFile(self):
        subprocess.Popen(fr'explorer /select,"{self.csv_path}"')
        self.progressBar.setProperty("value", 0)
        self.lbl_message.setVisible(False)
        self.btn_open.setVisible(False)
        
class ExtractThread(QThread):
    signal_pbar = pyqtSignal(int, name="updateProgressBar")
    signal_save_csv = pyqtSignal(list, str, name="saveCSVFile")
    signal_messagebox = pyqtSignal(str, str, name="showMessageBox")
    def __init__(self, product_name, number_pages, amazon_sold, amazon_ships, amazon_stars):
        QThread.__init__(self)
        self.product_name = product_name
        self.number_pages = number_pages
        self.amazon_sold = amazon_sold
        self.amazon_ships = amazon_ships
        self.amazon_stars = amazon_stars

    def __del__(self):
        self.wait()

    def run(self):
        scrapeAmazon = ScrapeAmazon()
        products_array = scrapeAmazon.scrape_amazon_products(self.product_name, self.number_pages, self.signal_pbar, self.amazon_sold, self.amazon_ships, self.amazon_stars)
        self.signal_pbar.emit(100)
        self.signal_save_csv.emit(products_array, 'data_csv')
        # rows_count = data.size
        # for i, row in enumerate(data.iterrows()):
        #     url_to_extract = row[1][0]
        #     if 'http' not in url_to_extract:
        #         url_to_extract = 'https://' + str(url_to_extract)
        #     print(url_to_extract)
        #     array_urls.append(url_to_extract)
        #     phones_extract = extract_product_by_url(url_to_extract)
        #     if phones_extract is not None:
        #         phones_extract = list(dict.fromkeys(phones_extract))
        #     if phones_extract is None:
        #         array_phones.append("error")
        #     elif len(phones_extract) == 0:
        #         array_phones.append("no phones found")
        #     else:
        #         print("Phone: " + str(phones_extract))
        #         array_phones.append(";".join(phones_extract))
        #     value = round(int(i + 1) / rows_count * 100)
        #     self.signal_pbar.emit(value)
        # 
        # self.signal_save_csv.emit(array_urls, array_phones, 'data_csv')
        # self.signal_messagebox.emit("information", "Extract finish!")

class WindowAbout(QWidget):
    def __init__(self):
        super(WindowAbout, self).__init__()

        self.resize(269, 204)
        self.setFixedSize(self.size())
        self.label = QLabel(self)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 50, 131, 31))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label_2 = QLabel(self)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 80, 71, 16))
        self.label_3 = QLabel(self)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 141, 31))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 100, 221, 16))
        self.label_5 = QLabel(self)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 120, 171, 16))
        self.label_6 = QLabel(self)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 140, 161, 16))
        self.retranslateUi(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", u"About", None))
        self.label.setText(_translate("Form", u"Amazon extractor", None))
        self.label_2.setText(_translate("Form", u"Version 1.0", None))
        self.label_3.setText(_translate("Form", u"About this app", None))
        self.label_4.setText(_translate("Form", u"\u00a9 2022 All rights reserved.", None))
        self.label_5.setText(_translate("Form", u"For questions or support, contact us", None))
        self.label_6.setText(_translate("Form", u"info@okscraping.com", None))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon(os.path.join(basedir, 'icons/app.ico')))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
